Resources:
  GameshopEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0129bfde49ddb0ed6 #AMI ID Instances ec2
      KeyName: AmazonWS-MSP-KeyPair #My own key
      SecurityGroupIds:
        - sg-064f1025af40fdd71
      Tags:
        - Key: Name
          Value: GameshopEC2Instance

  GameDynamoDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GameshopDB
      AttributeDefinitions:
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: gameId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5